### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-1-evaluacion-final-BMatillaVaras#1]
Muy buen trabajo @BMatillaVaras!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 377 / 429
- [x] HTML > ATRIBUTOS: Todos los `img` deben tener el atributo `title`.
- [x] HTML > HAMBURGUESA: El menú de la hamburguesa debe tener un `nav`.
- [x] HTML > HERO: El texto del título del hero debe ser: Anonymous proxy.

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te encaja dímelo cuanto antes por favor.

> Para corregir el ejercicio buscamos determinadas palabras en el código para identificar las secciones. Por ejemplo buscamos **Anonymous** para buscar el hero. Si has escrito mal alguna palabra en el código es posible que te aparezcan aquí falsos errores.

Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by BMatillaVaras** [comment]
Creo que el que has comentado en la entrevista que sí había hecho era el del Hero, pero en realidad sí era un fallo, porque había puesto en mi código Proxy, con la P mayúscula en vez de minúscula, aunque luego en el css le daba uppercase, jeje, ya está cambiado también.
